FROM node:22.16.0-alpine3.22

# Crea grupo y usuario
RUN addgroup nodeapp && adduser -S -G nodeapp nodeapp

# Instala Chromium y dependencias necesarias para Puppeteer
RUN apk update && apk add --no-cache \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    bash \
    udev \
    mesa-gl \
    && rm -rf /var/cache/apk/*

# Configura Puppeteer para usar Chromium del sistema
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

# Establece directorio de trabajo
WORKDIR /app/

# Copia package.json y package-lock.json y ajusta propietario
COPY --chown=nodeapp package*.json ./

# Instala dependencias como root y ajusta permisos para nodeapp
RUN npm install && chown -R nodeapp:nodeapp /app/node_modules

# Copia el resto del código y ajusta propietario
COPY --chown=nodeapp . .

# Cambia al usuario sin privilegios
USER nodeapp

EXPOSE 3002
CMD ["npm", "start"]
