FROM node:22.16.0-alpine3.22
RUN addgroup nodeapp && adduser -S -G nodeapp nodeapp
USER nodeapp
WORKDIR /app/
COPY --chown=nodeapp package*.json .
RUN npm install
COPY --chown=nodeapp . .
EXPOSE 3002
CMD ["npm", "start"]