services:
  rabbitmq_eco:
    image: rabbitmq:3.13.7-management-alpine
    restart: always
    container_name: rabbitmq_eco
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - app_network
  db_proyect:
    image: mongo:8.0.10-rc0-noble
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    networks:
      - app_network
    volumes:
      - dataNoSQL:/data/db
  token_cache:
    image: redis:7.4.4-alpine3.21
    restart: always
    container_name: token_cache
    networks:
      - app_network
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v1.8.7
    restart: always
    environment:
      AUTHENTICATION_API_KEY: admin
      DASHBOARD: true
    networks:
      - app_network
    volumes:
      - evolution_instances:/evolution/instances
networks:
  app_network:
    driver: bridge

volumes:
  dataNoSQL:
  evolution_instances:
